import { expect, test, type Page } from "@playwright/test";

import { webOrigin } from "./config";

/**
 * The M8 discovery and SEO surfaces, against rendered responses.
 *
 * The unit suite already proves the serializers and the selection rules. What
 * it cannot prove is the part that only exists once the app is running: that
 * `robots.txt` and the sitemaps are actually reachable and publicly cacheable
 * rather than swallowed by the proxy's `private, no-store`, that a taxonomy
 * page renders and 404s correctly, and — the one that matters most —
 * that the `xhtml:link` alternates in the sitemap are byte-identical to the
 * `hreflang` links the article page emits. Those are generated by different
 * code paths from one DTO, and "identical" is only a property if something
 * compares them.
 */

const ARTICLE_SLUG_EN = "theme-token-matrix";
const ARTICLE_SLUG_FA = "ماتریس-تم";

async function textOf(page: Page, path: string): Promise<string> {
  const response = await page.request.get(`${webOrigin}${path}`);
  expect(response.status(), path).toBe(200);
  return response.text();
}

test.describe("robots and sitemaps", () => {
  test("robots.txt names the canonical sitemap and is publicly cacheable", async ({
    page,
  }) => {
    const response = await page.request.get(`${webOrigin}/robots.txt`);
    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toContain("text/plain");
    // The proxy stamps `private, no-store` on every public HTML response. A
    // feed or sitemap that inherited it would defeat every shared cache in
    // front of the site, which is why those paths are excluded there.
    expect(response.headers()["cache-control"]).toContain("public");

    const body = await response.text();
    expect(body).toContain(`Sitemap: ${webOrigin}/sitemap.xml`);
    expect(body).toContain("Disallow: /admin");
    expect(body).not.toContain("Disallow: /_next");
  });

  test("the sitemap index points at one sitemap per locale", async ({
    page,
  }) => {
    const body = await textOf(page, "/sitemap.xml");
    expect(body).toContain("<sitemapindex");
    expect(body).toContain(`<loc>${webOrigin}/en/sitemap.xml</loc>`);
    expect(body).toContain(`<loc>${webOrigin}/fa/sitemap.xml</loc>`);
  });

  test("a locale sitemap lists published articles and taxonomy pages only", async ({
    page,
  }) => {
    const body = await textOf(page, "/en/sitemap.xml");
    expect(body).toContain(
      `<loc>${webOrigin}/en/blog/${ARTICLE_SLUG_EN}</loc>`
    );
    expect(body).toContain(
      `<loc>${webOrigin}/en/blog/category/engineering</loc>`
    );
    expect(body).toContain(`<loc>${webOrigin}/en/blog</loc>`);
    // Cursor pages are `noindex` and their contents shift as articles are
    // published above them, so they are never canonical URLs.
    expect(body).not.toContain("cursor=");
    expect(body).not.toContain("/admin");
  });

  test("sitemap alternates match the article page's hreflang set exactly", async ({
    page,
  }) => {
    const sitemap = await textOf(page, "/en/sitemap.xml");
    const articleBlock = sitemap
      .split("<url>")
      .find((block) => block.includes(`/en/blog/${ARTICLE_SLUG_EN}<`));
    expect(articleBlock).toBeDefined();

    const sitemapAlternates = [
      ...(articleBlock ?? "").matchAll(/hreflang="([^"]+)"\s+href="([^"]+)"/g),
    ].map(([, hreflang, href]) => `${hreflang} ${href}`);

    await page.goto(`${webOrigin}/en/blog/${ARTICLE_SLUG_EN}`);
    const pageAlternates = await page
      .locator('head link[rel="alternate"][hreflang]')
      .evaluateAll((links) =>
        links.map(
          (link) =>
            `${link.getAttribute("hreflang")} ${(link as HTMLLinkElement).href}`
        )
      );

    expect(new Set(sitemapAlternates)).toEqual(new Set(pageAlternates));
    expect(sitemapAlternates).toContain(
      `x-default ${webOrigin}/en/blog/${ARTICLE_SLUG_EN}`
    );
  });
});

test.describe("per-locale feeds", () => {
  test("the English feed is RSS with a self link and summary items", async ({
    page,
  }) => {
    const response = await page.request.get(`${webOrigin}/en/blog/feed.xml`);
    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toContain("application/rss+xml");
    expect(response.headers()["cache-control"]).toContain("public");

    const body = await response.text();
    expect(body).toContain('<rss version="2.0"');
    expect(body).toContain(
      `<atom:link href="${webOrigin}/en/blog/feed.xml" rel="self"`
    );
    expect(body).toContain(
      `<guid isPermaLink="true">${webOrigin}/en/blog/${ARTICLE_SLUG_EN}</guid>`
    );
    // A summary feed: the rendered body is never syndicated, so there is no
    // second sanitization boundary to maintain for consumers nobody controls.
    expect(body).not.toContain("<pre");
    expect(body).not.toContain("shiki");
  });

  test("the Persian feed is its own channel in its own language", async ({
    page,
  }) => {
    const body = await textOf(page, "/fa/blog/feed.xml");
    // The site declares one language tag per locale (I18N.md §6), and it is
    // the same `bcp47` value the page's `lang` attribute and its `hreflang`
    // links carry. A feed is not the place to invent a regional variant.
    expect(body).toContain("<language>fa</language>");
    expect(body).toContain(encodeURIComponent(ARTICLE_SLUG_FA));
  });

  test("the blog index advertises the feed it actually serves", async ({
    page,
  }) => {
    await page.goto(`${webOrigin}/en/blog`);
    const href = await page
      .locator('head link[rel="alternate"][type="application/rss+xml"]')
      .first()
      .getAttribute("href");
    expect(href).toContain("/en/blog/feed.xml");
  });
});

test.describe("taxonomy pages", () => {
  test("a category page lists its articles and carries breadcrumbs", async ({
    page,
  }) => {
    await page.goto(`${webOrigin}/en/blog/category/engineering`);
    await expect(
      page.getByRole("heading", { level: 1, name: /Engineering/ })
    ).toBeVisible();
    await expect(
      page.getByRole("link", { name: "Theme token matrix" })
    ).toBeVisible();

    const canonical = await page
      .locator('head link[rel="canonical"]')
      .getAttribute("href");
    expect(canonical).toBe(`${webOrigin}/en/blog/category/engineering`);

    const structuredData = await page
      .locator('script[type="application/ld+json"]')
      .allTextContents();
    expect(
      structuredData.some((json) => json.includes('"CollectionPage"'))
    ).toBe(true);
    expect(
      structuredData.some((json) => json.includes('"BreadcrumbList"'))
    ).toBe(true);
  });

  test("a tag page is reachable from the article it describes", async ({
    page,
  }) => {
    await page.goto(`${webOrigin}/en/blog/${ARTICLE_SLUG_EN}`);
    await page
      .getByRole("link", { name: /TypeScript/ })
      .first()
      .click();
    await expect(page).toHaveURL(`${webOrigin}/en/blog/tag/typescript`);
  });

  test("an unknown term is a 404, not an empty page", async ({ page }) => {
    const response = await page.request.get(
      `${webOrigin}/en/blog/category/never-published`
    );
    expect(response.status()).toBe(404);
  });
});
