"use client";

import { scrollToSection } from "@/Components/SmoothScroll/SmoothScroll";
import type {
  BlogFontKey,
  BlogSizeStep,
} from "@portfolio/contracts/appearance";
import { useEffect, useRef } from "react";

interface ArticleHeading {
  readonly depth: number;
  readonly id: string;
  readonly text: string;
}

export function ArticleTableOfContents({
  headings,
  label,
}: {
  readonly headings: readonly ArticleHeading[];
  readonly label: string;
}) {
  useEffect(() => {
    if (window.location.hash.length <= 1) return;
    const frame = window.requestAnimationFrame(() => {
      scrollToSection(window.location.hash);
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);

  return (
    <nav aria-label={label} className="border-border border p-4">
      <h2 className="mb-3 font-semibold">{label}</h2>
      <ol className="space-y-1">
        {headings.map((heading) => (
          <li key={heading.id} className={headingIndent(heading.depth)}>
            <a
              href={`#${heading.id}`}
              className="underline"
              onClick={(event) => {
                if (
                  event.button !== 0 ||
                  event.metaKey ||
                  event.ctrlKey ||
                  event.shiftKey ||
                  event.altKey
                ) {
                  return;
                }
                if (!scrollToSection(`#${heading.id}`)) return;
                event.preventDefault();
                window.history.replaceState(null, "", `#${heading.id}`);
              }}
            >
              {heading.text}
            </a>
          </li>
        ))}
      </ol>
    </nav>
  );
}

export function ArticleReadingSurface({
  html,
  font,
  size,
  copyLabel,
  copiedLabel,
  copyFailedLabel,
}: {
  readonly html: string;
  readonly font: BlogFontKey;
  readonly size: BlogSizeStep;
  readonly copyLabel: string;
  readonly copiedLabel: string;
  readonly copyFailedLabel: string;
}) {
  const surfaceRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const surface = surfaceRef.current;
    if (surface === null) return;

    // The Markdown renderer includes heading permalinks for clients that want
    // them. They add a bare `#` to this reading layout, while the separate
    // table of contents already provides navigation, so remove only the exact
    // generated permalink and leave authored heading links untouched.
    for (const heading of surface.querySelectorAll("h2, h3, h4, h5, h6")) {
      const permalink = heading.firstElementChild;
      if (
        heading.id.length > 0 &&
        permalink instanceof HTMLAnchorElement &&
        permalink.textContent?.trim() === "#" &&
        permalink.getAttribute("href") === `#${heading.id}`
      ) {
        permalink.remove();
      }
    }

    const cleanups: Array<() => void> = [];
    for (const pre of surface.querySelectorAll("pre")) {
      const code = pre.querySelector("code");
      if (code === null || pre.querySelector(".code-copy-button") !== null) {
        continue;
      }

      const button = createCopyButton(copyLabel);
      let resetTimer: number | undefined;
      const onClick = async () => {
        if (resetTimer !== undefined) window.clearTimeout(resetTimer);
        try {
          await copyText(code.textContent ?? "");
          button.dataset.copyState = "copied";
          button.setAttribute("aria-label", copiedLabel);
          button.title = copiedLabel;
        } catch {
          button.dataset.copyState = "failed";
          button.setAttribute("aria-label", copyFailedLabel);
          button.title = copyFailedLabel;
        }
        resetTimer = window.setTimeout(() => {
          button.dataset.copyState = "idle";
          button.setAttribute("aria-label", copyLabel);
          button.title = copyLabel;
        }, 2_000);
      };

      button.addEventListener("click", onClick);
      pre.append(button);
      cleanups.push(() => {
        if (resetTimer !== undefined) window.clearTimeout(resetTimer);
        button.removeEventListener("click", onClick);
        button.remove();
      });
    }

    return () => cleanups.forEach((cleanup) => cleanup());
  }, [copyFailedLabel, copiedLabel, copyLabel, html]);

  return (
    <div
      ref={surfaceRef}
      className="blog-reading-surface"
      data-blog-font={font}
      data-blog-size={size}
      // `html` is generated by the sanitize-last server pipeline and validated
      // by the strict public DTO before it reaches this progressive enhancer.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function headingIndent(depth: number): string {
  if (depth === 3) return "ms-4";
  if (depth === 4) return "ms-8";
  if (depth === 5) return "ms-12";
  if (depth === 6) return "ms-16";
  return "";
}

function createCopyButton(label: string): HTMLButtonElement {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "code-copy-button";
  button.dataset.copyState = "idle";
  button.setAttribute("aria-label", label);
  button.title = label;
  button.append(createCopyIcon(), createCheckIcon());
  return button;
}

function createCopyIcon(): SVGSVGElement {
  const icon = createSvg("code-copy-icon");
  const back = document.createElementNS("http://www.w3.org/2000/svg", "rect");
  back.setAttribute("x", "8");
  back.setAttribute("y", "8");
  back.setAttribute("width", "10");
  back.setAttribute("height", "10");
  back.setAttribute("rx", "2");
  const front = document.createElementNS("http://www.w3.org/2000/svg", "path");
  front.setAttribute(
    "d",
    "M6 14H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v1"
  );
  icon.append(back, front);
  return icon;
}

function createCheckIcon(): SVGSVGElement {
  const icon = createSvg("code-copy-check-icon");
  const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
  path.setAttribute("d", "m5 11 4 4L19 5");
  icon.append(path);
  return icon;
}

function createSvg(className: string): SVGSVGElement {
  const icon = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  icon.setAttribute("class", className);
  icon.setAttribute("viewBox", "0 0 24 24");
  icon.setAttribute("width", "18");
  icon.setAttribute("height", "18");
  icon.setAttribute("fill", "none");
  icon.setAttribute("stroke", "currentColor");
  icon.setAttribute("stroke-width", "2");
  icon.setAttribute("stroke-linecap", "round");
  icon.setAttribute("stroke-linejoin", "round");
  icon.setAttribute("aria-hidden", "true");
  return icon;
}

async function copyText(text: string): Promise<void> {
  if (navigator.clipboard !== undefined) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const input = document.createElement("textarea");
  input.value = text;
  input.setAttribute("readonly", "");
  input.className = "sr-only";
  document.body.append(input);
  input.select();
  const copied = document.execCommand("copy");
  input.remove();
  if (!copied) throw new Error("Clipboard copy failed.");
}
