"use client";

import { FormEvent, useEffect, useState } from "react";

import { adminRequest, describeAdminError } from "./admin-client";

type Category = { readonly id: string; readonly key: string; readonly version: number; readonly enabled: boolean; readonly sortOrder: number; readonly translations: readonly { locale: string; name: string }[]; readonly skills: readonly { id: string; name: string; color: string; version: number }[] };

export default function AdminSkillsEditor(): React.JSX.Element {
  const [categories, setCategories] = useState<readonly Category[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const load = async () => { try { setCategories(await adminRequest<readonly Category[]>("/admin/skill-categories")); } catch (error) { setMessage(describeAdminError(error)); } };
  useEffect(() => { void load(); }, []);
  async function createCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const form = new FormData(event.currentTarget); setBusy(true); setMessage(null); try { await adminRequest("/admin/skill-categories", { method: "POST", mutation: true, body: { key: form.get("key"), enabled: true, sortOrder: Number(form.get("sortOrder")) } }); event.currentTarget.reset(); await load(); setMessage("Category created. Add its localized label before publishing it."); } catch (error) { setMessage(describeAdminError(error)); } finally { setBusy(false); } }
  async function createSkill(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const form = new FormData(event.currentTarget); setBusy(true); setMessage(null); try { await adminRequest("/admin/skills", { method: "POST", mutation: true, body: { categoryId: form.get("categoryId"), name: form.get("name"), color: form.get("color"), iconMediaId: null, enabled: true, sortOrder: Number(form.get("sortOrder")) } }); event.currentTarget.reset(); await load(); setMessage("Skill created."); } catch (error) { setMessage(describeAdminError(error)); } finally { setBusy(false); } }
  return <section className="flex flex-col gap-5"><div><h2 className="text-lg font-semibold">Skills</h2><p className="text-text-muted text-sm">Skill names remain proper nouns. Category labels are localized separately.</p></div><p aria-live="polite" className={message?.includes("created") ? "text-success text-sm" : "text-text-muted text-sm"}>{message ?? `${categories.length} categories.`}</p><div className="grid gap-5 lg:grid-cols-2"><form onSubmit={(event) => void createCategory(event)} className="border-border flex flex-col gap-3 border p-4"><h3 className="font-semibold">Add category</h3><label>Key<input className="FormInput" name="key" required pattern="[a-z][a-z0-9]*(?:-[a-z0-9]+)*" /></label><label>Order<input className="FormInput" name="sortOrder" type="number" min="0" defaultValue="0" required /></label><button className="border-border border p-2 disabled:opacity-60" disabled={busy}>Create category</button></form><form onSubmit={(event) => void createSkill(event)} className="border-border flex flex-col gap-3 border p-4"><h3 className="font-semibold">Add skill</h3><label>Category<select className="FormInput" name="categoryId" required defaultValue=""> <option value="" disabled>Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.translations.find((item) => item.locale === "en")?.name ?? category.key}</option>)}</select></label><label>Name<input className="FormInput" name="name" required /></label><label>Colour<input className="FormInput" name="color" required defaultValue="#0070f3" pattern="#[0-9a-fA-F]{6}" /></label><label>Order<input className="FormInput" name="sortOrder" type="number" min="0" defaultValue="0" required /></label><button className="border-border border p-2 disabled:opacity-60" disabled={busy}>Create skill</button></form></div><ul className="flex flex-col gap-3">{categories.map((category) => <li className="border-border border p-4" key={category.id}><h3 className="font-semibold">{category.translations.find((item) => item.locale === "en")?.name ?? category.key}</h3><p className="text-text-muted text-sm">{category.skills.map((skill) => skill.name).join(", ") || "No skills yet."}</p></li>)}</ul></section>;
}
